### ISSUE TITLE
Multiple '*' fails .....

### ISSUE THREAD

**Issue by pprocacci** [zostay/perl6-IO-Glob#12]
Perl 5 (works):
`glob('/some/path/*/*/file.json');`

BSD - /bin/ls (works)
`ls -l /some/path/*/*/file.json`

Perl6 - (Doesn't work)
`glob('/some/path/*/*/file.json');`

The failure occurs because not all directory contents of the first glob '*' is a directory.
When it encounters something other than a directory it fails.  It should continue without error considering it doesn't match the original RE.

**Comment by zostay** [comment]
Thanks. v0.5 was just released to CPAN and includes this fix. Cheers.

**Comment by pprocacci** [comment]
Thanks.  I'm not sure if it's the change you made for this, or something else but now .....

`
for glob('/some/nested/dir/*/*/file.json') -> $files {
  say ~$files;
}`

Results in:
`Type check failed in assignment to @!terms; expected <anon> but got Any (Any)
  in submethod BUILDALL at /home/user/.perl6/sources/D091B042962D62C8BF5D7BAEAE10E39E4BF6BDDA (IO::Glob) line 59
  in method compile-globs at /home/user/.perl6/sources/D091B042962D62C8BF5D7BAEAE10E39E4BF6BDDA (IO::Glob) line 343
  in method dir at /home/user/.perl6/sources/D091B042962D62C8BF5D7BAEAE10E39E4BF6BDDA (IO::Glob) line 374
  in method iterator at /home/user/.perl6/sources/D091B042962D62C8BF5D7BAEAE10E39E4BF6BDDA (IO::Glob) line 349
  in block <unit> at ./test.pl6 line 5`
