### ISSUE TITLE
Type check failed in assignment to @!terms

### ISSUE THREAD

**Issue by zostay** [zostay/perl6-IO-Glob#13]
@pprocacci says in issue #12 reporting a new issue:

Thanks.  I'm not sure if it's the change you made for this, or something else but now .....

`
for glob('/some/nested/dir/*/*/file.json') -> $files {
  say ~$files;
}`

Results in:
`Type check failed in assignment to @!terms; expected <anon> but got Any (Any)
  in submethod BUILDALL at /home/user/.perl6/sources/D091B042962D62C8BF5D7BAEAE10E39E4BF6BDDA (IO::Glob) line 59
  in method compile-globs at /home/user/.perl6/sources/D091B042962D62C8BF5D7BAEAE10E39E4BF6BDDA (IO::Glob) line 343
  in method dir at /home/user/.perl6/sources/D091B042962D62C8BF5D7BAEAE10E39E4BF6BDDA (IO::Glob) line 374
  in method iterator at /home/user/.perl6/sources/D091B042962D62C8BF5D7BAEAE10E39E4BF6BDDA (IO::Glob) line 349
  in block <unit> at ./test.pl6 line 5`

**Comment by pprocacci** [comment]
A clean install of perl6 and related modules solved the problem.
I can't explain how or why, but it _IS_ working.

**Comment by zostay** [comment]
Yeah, I can't reproduce this one.
