### ISSUE TITLE
Absolute paths fail

### ISSUE THREAD

**Issue by 0racle** [zostay/perl6-IO-Glob#15]
Any path I try to glob that begins with '/' yields the following error

```
Type check failed in assignment to @!terms; expected <anon> but got Any (Any)
  in method compile-globs at ... (IO::Glob) line 342           
  in method dir at ... (IO::Glob) line 373
```

If I `chdir` to `/` first, and drop the leading `/` from my glob pattern, it works fine.

**Comment by zostay** [comment]
Sorry it took me awhile to figure this one out. I just released v0.7.0 to CPAN which fixes this. It does have one wrinkle, which is that this works:

```
glob('/*').dir('/');
```

And this works:

```
glob('*').dir('/');
```

But this does not:

```
glob("/*").dir
```

That will cause an exception. If someone wants to use an absolute glob, then they must also explicitly specify an absolute path in the dir method call as well.
