### ISSUE TITLE
Missing source-url meta info

### ISSUE THREAD

**Issue by ldidry** [zostay/perl6-IO-Glob#3]
Hello,

I tried to install IO::Glob from `panda`: it fails to fetch it because of `fetch stage failed for IO::Glob: source-url meta info missing`.

Could you add it to `META6.json`? Thank you.

Panda 0.1, Perl 6.c, freshly updated with rakudobrew.

**Comment by zostay** [comment]
I'll add it. It's hard to know what's actually required since the specs on META6.json are all over the map. :8ball:

**Comment by zostay** [comment]
Fixed in master.

**Comment by ldidry** [comment]
Thank you! Yes, it's a new world, hard to change our habits :wink:
